---
# tasks file for roles/ufw
- name: TEMPLATE | Configure UFW service state
  block:
    - name: Configuring service
      notify: reload ufw
      when: ufw_config_manage | bool
      ansible.builtin.template:
        src: "{{ ufw_config_file | basename }}.j2"
        dest: "{{ ufw_config_file }}"
        mode: "0644"
